### ISSUE TITLE
cast to bool for working version

### ISSUE THREAD

**Issue by lindesbs** [nickw444/flask-ldap3-login#123]
https://github.com/nickw444/flask-ldap3-login/blob/e9fb8072041dc6ddde7d6dbd5c5d162cbfbcfcc5/flask_ldap3_login/__init__.py#L377

`current_app.config.get("LDAP_SEARCH_FOR_GROUPS")` return **string**

```
    if bool(current_app.config.get("LDAP_SEARCH_FOR_GROUPS")):
                response.user_groups = self.get_user_groups(
                    dn=bind_user, _connection=connection
                )

```

**Comment by nickw444** [comment]
This seems like a configuration issue, rather than a library implementation issue - `LDAP_SEARCH_FOR_GROUPS` should be provided a `bool` type value from flask config when config is defined.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/10ba8bc6-8e09-44b9-b929-3cf566cc0897">
