### ISSUE TITLE
Changing port for configuration

### ISSUE THREAD

**Issue by jctj** [nickw444/flask-ldap3-login#36]
Nick - first, thanks for writing this. LDAP configuration is driving me nuts....

My school has limited resources and so IT is only able to help me so much. I have tried to use your LDAP3-LoginManager with no luck so far. I believe I have all the setting correct, but I cannot see a config dict option for changing/setting the port. Our school LDAP port is 636, so I do not  know if that is the standard port or a different port than normal. Is there an LDAP_Port option for the config dict?

Thanks,

James Taylor

**Comment by jctj** [comment]
Sorry - nevermind. I found in your files the following:
```
self.config.update(config)

        self.config.setdefault('LDAP_PORT', 389)
        self.config.setdefault('LDAP_HOST', None)
```
...
I was so close - should have realized that the key would be in all caps, just like all the other keys.... 

Now I am getting:` error receiving data: [WinError 10054] An existing connection was forcibly closed by the remote host`. Time to chase down another problem.

Thanks,

James

**Comment by nickw444** [comment]
Hi James,

You can find the full documentation [here](http://flask-ldap3-login.readthedocs.io/en/latest/) and in particular you can find the documentation for the available configuration options [here](http://flask-ldap3-login.readthedocs.io/en/latest/configuration.html)

I will close this issue since it seems you have resolved the port issue. If you experience other problems with the library please raise another issue. Thanks.

**Comment by jctj** [comment]
Thanks Nick!


On July 30, 2018 at 5:31:22 PM, Nick Whyte (notifications@github.com) wrote:

Hi James,

You can find the full documentation here and in particular you can find the documentation for the available configuration options here

I will close this issue since it seems you have resolved the port issue. If you experience other problems with the library please raise another issue. Thanks.
